name: Test-Build

on:
  workflow_dispatch:
  push:


permissions:
  contents: write

jobs:
  Test-Build:
    name: Test-Build
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test-Build
        uses: PSModule/GitHub-Script@v1
        with:
          Script: |
            ./PSModule/build.ps1
            Get-ChildItem -Recurse | Select-Object -ExpandProperty FullName | Sort-Object

      - name: Test-Build
        uses: PSModule/GitHub-Script@v1
        with:
          Script: |
            . src/main.ps1
            . src/functions/private/Initialize-Sodium.ps1
            Initialize-Sodium
