name: Build-Test

on:
  workflow_dispatch:
  push:


permissions:
  contents: write

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build
        uses: PSModule/GitHub-Script@v1
        with:
          Script: |
            ./PSModule/build.ps1
            Get-ChildItem -Recurse | Select-Object -ExpandProperty FullName | Sort-Object¨
            Copy-Item -Path examples/GitHubSecretService.ps1 -Destination ./src/GitHubSecretService.ps1

      # Upload articats
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Sodium
          path: ./src

  Test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Download artifacts
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Sodium
          path: ./src

      - name: Test
        uses: PSModule/GitHub-Script@v1
        with:
          Script: |
            . src/main.ps1
            Get-ChildItem 'src/functions/' -Recurse -File | ForEach-Object { . $_.FullName }
            . src/GitHubSecretService.ps1
