name: Test-Build

on:
  workflow_dispatch:
  push:


permissions:
  contents: write

jobs:
  Test-Build:
    name: Test-Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test-Build
        uses: PSModule/GitHub-Script@v1
        with:
          Script: ./PSModule/build.ps1

      - name: Debug
        uses: PSModule/Debug@v0
